version: "3.3"

networks:

  monitor:
    external: true

  proxy:
    external: true

  logging:
    external: true

services:

  grafana:
    image: basi/grafana:${GRAFANA_VERSION:-4.6.2}
    networks:
      - monitor
      - logging
      - proxy
    volumes:
      - grafana:/var/lib/grafana/
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/
      - GF_SECURITY_ADMIN_USER=${GF_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD:-admin}
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
      - ELASTICSEARCH_ENDPOINT=${ES_ADDRESS:-http://elasticsearch:9200}
      - ELASTICSEARCH_USER=${ES_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ES_PASSWORD}
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
        reservations:
          cpus: '0.50'
          memory: 64M
      placement:
        constraints: 
          - node.role == worker
      restart_policy:
        delay: 30s
      labels:
        - com.df.notify=true
        - com.df.port=3000
        - com.df.serviceDomain=${GRAFANA_DOMAIN:-localhost}
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s

volumes:

  grafana:
    driver: cloudstor:aws
    external: false